from turtle import *
screen = getscreen()
screen.bgcolor("black")
speed(0)
def draw_rectangle(fcolor, y):
    penup()
    goto(-150, y)
    pendown()
    color("black", fcolor)
    begin_fill()
    for _ in range(2):
        forward(300)
        right(90)
        forward(50)
        right(90)
    end_fill()
draw_rectangle("orange", 100)
draw_rectangle("white", 50)
draw_rectangle("green", 0)
penup()
goto(0, 0)
setheading(0)
pendown()
color("blue")
circle(25)
penup()
goto(0, 25)
setheading(0)
pendown()
for _ in range(24):
    forward(25)
    backward(25)
    left(15)
hideturtle()
done()
